route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'Prometheus'
            channel: '#operations'
            api_url: 'https://hooks.slack.com/services/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'
