# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'Alertmanager'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'snmp'
    params:
      module: [default]
    static_configs:
      - targets:
          - 10.0.0.1
          - 10.0.0.5
          # - 10.0.1.11
          # - 10.0.1.11
          # - 10.0.1.70
          # - 10.0.1.90
          # - 10.0.1.100
          # - 10.0.1.171
          # - 10.0.1.191
          # - 10.0.1.200
          # - 10.255.255.1
          # - 10.255.255.2
          # - 10.255.255.3
          # - 10.255.255.4
          # - 10.255.255.5
          # - 10.255.255.6
          # - 10.255.255.7
          # - 10.255.255.8
          # - 10.255.255.9
          # - 10.255.255.10
          # - 10.255.255.11
          # - 10.255.255.12
          # - 10.255.255.13
          # - 10.255.255.14
          # - 10.255.255.111
          # - 10.255.255.222
          # - 10.255.255.250
          # - 10.255.255.251
          # - 10.255.255.253
          # - 10.255.255.254
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_address
      - source_labels: [__param_address]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # SNMP exporter.
